return {
    suites = {
        { "loader"      , "tests/loader.lua" },
        { "startup"     , "tests/startup.lua" },
        { "swift_lsp"   , "tests/swift_lsp.lua" },
        { "semantics_lsp", "tests/semantics_lsp.lua" },
        { "lsp_tooling" , "tests/lsp_tooling.lua" },
        { "lsp_diagnostic_copy", "tests/lsp_diagnostic_copy.lua" },
        { "lsp_symbol_library", "tests/lsp_symbol_library.lua" },
        { "format"       , "tests/format.lua" },
        { "casecon_substitute", "tests/casecon_substitute.lua" },
        { "output"       , "tests/output.lua" },
        { "nicetstamp"   , "tests/nicetstamp.lua" },
        { "confirm"     , "tests/confirm.lua" },
        { "boot"        , "tests/boot.lua" },
        { "funcs"       , "tests/funcs.lua" },
        { "indentation" , "tests/indentation.lua" },
        { "filetype"    , "tests/filetype.lua" },
        { "file_rename" , "tests/file_rename.lua" },
        { "filemover"   , "tests/filemover.lua" },
        { "performance", "tests/performance.lua" },
        { "deferred", "tests/deferred.lua" },
        { "trash"       , "tests/trash.lua" },
        { "netrw_batch" , "tests/netrw_batch.lua" },
        { "trash_ui"    , "tests/trash_ui.lua" },
    },
}
